### ISSUE TITLE
Allow active li in view on load question

### ISSUE THREAD

**Issue by andrewminton** [lisaogren/hoverscroll#1]
Hi there,

Not so much an issue but a feature query.

I am using this script on a series of li items. I have limited the height in my vertical list and am assigning an active class to the value of a clicked item. 

Is there part of the script I could hook into to aways have the active list item in view no matter where it is in the list?

So on loading the page, the li.active item would calculate the total height of the list, total height of the hoverscroll wrapper and determine if it's inside the visible zone?

Any pointers?

**Comment by ghost** [comment]
Hi!

I don't really understand the purpose of your feature,

Would it be to block the scrolling so that it keeps the li.active in the view or would it be to change the active item when the current li.active scrolls out of the view ?

Or is the feature only supposed to be executed upon page load, and thus scroll the li.active into the view upon loading ?

I think you'll need to modify the code slightly to incorporate a hook to which you could attach your code.
I'll tell you where to put your code when understand a bit more what you are trying to achieve.

Cheers

**Comment by andrewminton** [comment]
Hi,

Thanks for reply.

It's to allow the execution on page load to present the active li into view.

Please let me know where about's I should be looking and I'll dig in.

Thanks again.

**Comment by ghost** [comment]
I created a hook for you in the script. I hope that it fits your needs =) the example is in the commit comment. Cheers

**Comment by andrewminton** [comment]
Thanks Carl, much appreciated.

Is scrollTop() the best method for overriding the plugins first position on load?

Looking through your code, you use scrollTop for the move() function right?

**Comment by ghost** [comment]
Yes the scrollTop value would be the value you need to modify. In the
create callback you can access the scroll element quite simply. For example
:

$("#my-list").hoverscroll({
  vertical: true,
  create: function() {
    $(this).parent().scrollTop(500);
  }
});

Cheers

On Sun, Aug 5, 2012 at 8:36 PM, andrewminton <
reply@reply.github.com

> wrote:
> 
> Thanks Carl, much appreciated.
> 
> Id scrollTop() the best method for overriding the plugins first position
> on load?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/RasCarlito/hoverscroll/issues/1#issuecomment-7511974

## 

Carl

**Comment by andrewminton** [comment]
Thanks for confirmation Carl!

Loving this extension.
